const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{BACKGROUND: 0},
	{Sólido: 0},
	{CHAORETO: 0},
	{Fixar: 0},
	{NOEL: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{JOGAVEL: 0},
	{Teclado: 0},
	{Senóide: 0},
	{presente: 0},
	{panetone: 0},
	{Âncora: 0},
	{pontuaçao: 0},
	{ICEBOX: 0},
	{CRISTAL: 0},
	{IGLU: 0},
	{Sprite: 0},
	{ação: 0},
	{grinch: 0},
	{marcador: 0},
	{FINALGRINCH: 0},
	{TelaGameOver: 0},
	{ZonaDeChegada: 0},
	{igludeslizar: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{TELADEINICIO: 0},
	{Botão: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{pontos: 0}
];

self.InstanceType = {
	BACKGROUND: class extends self.ITiledBackgroundInstance {},
	CHAORETO: class extends self.ITiledBackgroundInstance {},
	NOEL: class extends self.ISpriteInstance {},
	JOGAVEL: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	presente: class extends self.ISpriteInstance {},
	panetone: class extends self.ISpriteInstance {},
	pontuaçao: class extends self.ITextInstance {},
	ICEBOX: class extends self.ISpriteInstance {},
	CRISTAL: class extends self.ISpriteInstance {},
	IGLU: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	grinch: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	FINALGRINCH: class extends self.ISpriteInstance {},
	TelaGameOver: class extends self.ITiledBackgroundInstance {},
	ZonaDeChegada: class extends self.ISpriteInstance {},
	igludeslizar: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	TELADEINICIO: class extends self.ITiledBackgroundInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}